/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author hector
 */
public class telaSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form telaSecretaria
     */
    public telaSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarPasciente = new javax.swing.JButton();
        botaoAtualizarPasciente = new javax.swing.JButton();
        botaoRemoverPasciente = new javax.swing.JButton();
        botaoCadastrarConsulta = new javax.swing.JButton();
        botaoAtualizarConsulta = new javax.swing.JButton();
        botaoRemoverConsulta = new javax.swing.JButton();
        botaoGerarRelatorioConsulta = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        labelMenuSecretaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastrarPasciente.setText("Cadastrar pasciente");

        botaoAtualizarPasciente.setText("Atualizar pasciente");

        botaoRemoverPasciente.setText("Remover pasciente");

        botaoCadastrarConsulta.setText("Cadastrar Consulta");

        botaoAtualizarConsulta.setText("Atualizar consulta");

        botaoRemoverConsulta.setText("Remover consulta");

        botaoGerarRelatorioConsulta.setText("Gerar relatório consulta");
        botaoGerarRelatorioConsulta.setToolTipText("");

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicar(evt);
            }
        });

        labelMenuSecretaria.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        labelMenuSecretaria.setText("Menu da Secretária");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoCadastrarPasciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAtualizarPasciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoRemoverPasciente)
                            .addComponent(botaoCadastrarConsulta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoRemoverConsulta)
                                .addGap(18, 18, 18)
                                .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoAtualizarConsulta)
                                .addGap(18, 18, 18)
                                .addComponent(botaoGerarRelatorioConsulta))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(labelMenuSecretaria)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelMenuSecretaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGerarRelatorioConsulta)
                    .addComponent(botaoAtualizarConsulta)
                    .addComponent(botaoRemoverPasciente)
                    .addComponent(botaoCadastrarPasciente))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizarPasciente)
                    .addComponent(botaoCadastrarConsulta)
                    .addComponent(botaoRemoverConsulta)
                    .addComponent(botaoSair))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clicar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicar
        System.exit(0);
    }//GEN-LAST:event_clicar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarConsulta;
    private javax.swing.JButton botaoAtualizarPasciente;
    private javax.swing.JButton botaoCadastrarConsulta;
    private javax.swing.JButton botaoCadastrarPasciente;
    private javax.swing.JButton botaoGerarRelatorioConsulta;
    private javax.swing.JButton botaoRemoverConsulta;
    private javax.swing.JButton botaoRemoverPasciente;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel labelMenuSecretaria;
    // End of variables declaration//GEN-END:variables
}
