/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author hector
 */
public class telaMedico extends javax.swing.JFrame {

    /**
     * Creates new form telaMedico
     */
    public telaMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarDadosAdicionais = new javax.swing.JButton();
        botaoAtualizarDadosAdicionais = new javax.swing.JButton();
        botaoRemoverDadosAdicionais = new javax.swing.JButton();
        botaoCadastrarProntuario = new javax.swing.JButton();
        botaoAtualizarProntuario = new javax.swing.JButton();
        botaoRemoverProntuario = new javax.swing.JButton();
        botaoGerarRelatorio = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        labelMenuMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoCadastrarDadosAdicionais.setText("Cadastrar dados \nadicionais");

        botaoAtualizarDadosAdicionais.setText("Atualizar dados adicionais");
        botaoAtualizarDadosAdicionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarDadosAdicionaisActionPerformed(evt);
            }
        });

        botaoRemoverDadosAdicionais.setText("remover dados adicionais");

        botaoCadastrarProntuario.setText("Cadastrar prontuario");

        botaoAtualizarProntuario.setText("Atualizar prontuario");
        botaoAtualizarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarProntuarioActionPerformed(evt);
            }
        });

        botaoRemoverProntuario.setText("Remover prontuario");

        botaoGerarRelatorio.setText("Gerar relatorio medico");

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clicar(evt);
            }
        });

        labelMenuMedico.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        labelMenuMedico.setText("Menu do Médico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoCadastrarDadosAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAtualizarDadosAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoRemoverDadosAdicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoCadastrarProntuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoAtualizarProntuario)
                            .addComponent(botaoRemoverProntuario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoGerarRelatorio)
                            .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(labelMenuMedico)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelMenuMedico)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoGerarRelatorio)
                    .addComponent(botaoCadastrarDadosAdicionais)
                    .addComponent(botaoRemoverDadosAdicionais)
                    .addComponent(botaoAtualizarProntuario))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(botaoAtualizarDadosAdicionais)
                    .addComponent(botaoCadastrarProntuario)
                    .addComponent(botaoRemoverProntuario))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAtualizarDadosAdicionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarDadosAdicionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAtualizarDadosAdicionaisActionPerformed

    private void clicar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clicar
        System.exit(0);
    }//GEN-LAST:event_clicar

    private void botaoAtualizarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarProntuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAtualizarProntuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizarDadosAdicionais;
    private javax.swing.JButton botaoAtualizarProntuario;
    private javax.swing.JButton botaoCadastrarDadosAdicionais;
    private javax.swing.JButton botaoCadastrarProntuario;
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JButton botaoRemoverDadosAdicionais;
    private javax.swing.JButton botaoRemoverProntuario;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel labelMenuMedico;
    // End of variables declaration//GEN-END:variables
}
